version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crypto_signals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for pub/sub and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Backend Node.js service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/crypto_signals
      REDIS_URL: redis://redis:6379
      BINANCE_API_KEY: ${BINANCE_API_KEY:-}
      BINANCE_SECRET: ${BINANCE_SECRET:-}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  # ML Training Service
  ml-service:
    build: ./ml
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/crypto_signals
    depends_on:
      - postgres
    volumes:
      - ./ml:/app

  # Frontend React app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_WS_URL: ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: